gdjs.ImpostazioniCode = {};
gdjs.ImpostazioniCode.localVariables = [];
gdjs.ImpostazioniCode.GDPositionPlaceholderObjects1= [];
gdjs.ImpostazioniCode.GDPositionPlaceholderObjects2= [];
gdjs.ImpostazioniCode.GDPositionPlaceholderObjects3= [];
gdjs.ImpostazioniCode.GDStarParticleObjects1= [];
gdjs.ImpostazioniCode.GDStarParticleObjects2= [];
gdjs.ImpostazioniCode.GDStarParticleObjects3= [];
gdjs.ImpostazioniCode.GDScreenFadeObjects1= [];
gdjs.ImpostazioniCode.GDScreenFadeObjects2= [];
gdjs.ImpostazioniCode.GDScreenFadeObjects3= [];
gdjs.ImpostazioniCode.GDCollezione_9595CartaObjects1= [];
gdjs.ImpostazioniCode.GDCollezione_9595CartaObjects2= [];
gdjs.ImpostazioniCode.GDCollezione_9595CartaObjects3= [];
gdjs.ImpostazioniCode.GDNuovo_9595GiocoObjects1= [];
gdjs.ImpostazioniCode.GDNuovo_9595GiocoObjects2= [];
gdjs.ImpostazioniCode.GDNuovo_9595GiocoObjects3= [];
gdjs.ImpostazioniCode.GDModalit_95224_9595a_9595tempoObjects1= [];
gdjs.ImpostazioniCode.GDModalit_95224_9595a_9595tempoObjects2= [];
gdjs.ImpostazioniCode.GDModalit_95224_9595a_9595tempoObjects3= [];
gdjs.ImpostazioniCode.GDNewTiledSpriteObjects1= [];
gdjs.ImpostazioniCode.GDNewTiledSpriteObjects2= [];
gdjs.ImpostazioniCode.GDNewTiledSpriteObjects3= [];
gdjs.ImpostazioniCode.GDGioca_9595e_9595imparaObjects1= [];
gdjs.ImpostazioniCode.GDGioca_9595e_9595imparaObjects2= [];
gdjs.ImpostazioniCode.GDGioca_9595e_9595imparaObjects3= [];
gdjs.ImpostazioniCode.GDNewTiledSprite2Objects1= [];
gdjs.ImpostazioniCode.GDNewTiledSprite2Objects2= [];
gdjs.ImpostazioniCode.GDNewTiledSprite2Objects3= [];
gdjs.ImpostazioniCode.GDMusicaObjects1= [];
gdjs.ImpostazioniCode.GDMusicaObjects2= [];
gdjs.ImpostazioniCode.GDMusicaObjects3= [];
gdjs.ImpostazioniCode.GDEFFETTIObjects1= [];
gdjs.ImpostazioniCode.GDEFFETTIObjects2= [];
gdjs.ImpostazioniCode.GDEFFETTIObjects3= [];
gdjs.ImpostazioniCode.GDVolume_9595musicaObjects1= [];
gdjs.ImpostazioniCode.GDVolume_9595musicaObjects2= [];
gdjs.ImpostazioniCode.GDVolume_9595musicaObjects3= [];
gdjs.ImpostazioniCode.GDVolume_9595EffettiObjects1= [];
gdjs.ImpostazioniCode.GDVolume_9595EffettiObjects2= [];
gdjs.ImpostazioniCode.GDVolume_9595EffettiObjects3= [];
gdjs.ImpostazioniCode.GDMuteObjects1= [];
gdjs.ImpostazioniCode.GDMuteObjects2= [];
gdjs.ImpostazioniCode.GDMuteObjects3= [];
gdjs.ImpostazioniCode.GDRiprovaObjects1= [];
gdjs.ImpostazioniCode.GDRiprovaObjects2= [];
gdjs.ImpostazioniCode.GDRiprovaObjects3= [];
gdjs.ImpostazioniCode.GDMen_95249Objects1= [];
gdjs.ImpostazioniCode.GDMen_95249Objects2= [];
gdjs.ImpostazioniCode.GDMen_95249Objects3= [];
gdjs.ImpostazioniCode.GDRiprendi8Objects1= [];
gdjs.ImpostazioniCode.GDRiprendi8Objects2= [];
gdjs.ImpostazioniCode.GDRiprendi8Objects3= [];
gdjs.ImpostazioniCode.GDPausaObjects1= [];
gdjs.ImpostazioniCode.GDPausaObjects2= [];
gdjs.ImpostazioniCode.GDPausaObjects3= [];
gdjs.ImpostazioniCode.GDOKObjects1= [];
gdjs.ImpostazioniCode.GDOKObjects2= [];
gdjs.ImpostazioniCode.GDOKObjects3= [];
gdjs.ImpostazioniCode.GDInserimento_9595nomeObjects1= [];
gdjs.ImpostazioniCode.GDInserimento_9595nomeObjects2= [];
gdjs.ImpostazioniCode.GDInserimento_9595nomeObjects3= [];
gdjs.ImpostazioniCode.GDCiaoObjects1= [];
gdjs.ImpostazioniCode.GDCiaoObjects2= [];
gdjs.ImpostazioniCode.GDCiaoObjects3= [];
gdjs.ImpostazioniCode.GDLivelloSucessivo3Objects1= [];
gdjs.ImpostazioniCode.GDLivelloSucessivo3Objects2= [];
gdjs.ImpostazioniCode.GDLivelloSucessivo3Objects3= [];
gdjs.ImpostazioniCode.GDTitoloObjects1= [];
gdjs.ImpostazioniCode.GDTitoloObjects2= [];
gdjs.ImpostazioniCode.GDTitoloObjects3= [];
gdjs.ImpostazioniCode.GDBlackBackgroundObjects1= [];
gdjs.ImpostazioniCode.GDBlackBackgroundObjects2= [];
gdjs.ImpostazioniCode.GDBlackBackgroundObjects3= [];
gdjs.ImpostazioniCode.GDSelectionObjects1= [];
gdjs.ImpostazioniCode.GDSelectionObjects2= [];
gdjs.ImpostazioniCode.GDSelectionObjects3= [];
gdjs.ImpostazioniCode.GDPunteggioObjects1= [];
gdjs.ImpostazioniCode.GDPunteggioObjects2= [];
gdjs.ImpostazioniCode.GDPunteggioObjects3= [];
gdjs.ImpostazioniCode.GDTempoTestoObjects1= [];
gdjs.ImpostazioniCode.GDTempoTestoObjects2= [];
gdjs.ImpostazioniCode.GDTempoTestoObjects3= [];
gdjs.ImpostazioniCode.GDCoppieObjects1= [];
gdjs.ImpostazioniCode.GDCoppieObjects2= [];
gdjs.ImpostazioniCode.GDCoppieObjects3= [];
gdjs.ImpostazioniCode.GDLivello6Objects1= [];
gdjs.ImpostazioniCode.GDLivello6Objects2= [];
gdjs.ImpostazioniCode.GDLivello6Objects3= [];
gdjs.ImpostazioniCode.GDLivello_95957Objects1= [];
gdjs.ImpostazioniCode.GDLivello_95957Objects2= [];
gdjs.ImpostazioniCode.GDLivello_95957Objects3= [];
gdjs.ImpostazioniCode.GDLivello1Objects1= [];
gdjs.ImpostazioniCode.GDLivello1Objects2= [];
gdjs.ImpostazioniCode.GDLivello1Objects3= [];
gdjs.ImpostazioniCode.GDLivello2Objects1= [];
gdjs.ImpostazioniCode.GDLivello2Objects2= [];
gdjs.ImpostazioniCode.GDLivello2Objects3= [];
gdjs.ImpostazioniCode.GDLivello3Objects1= [];
gdjs.ImpostazioniCode.GDLivello3Objects2= [];
gdjs.ImpostazioniCode.GDLivello3Objects3= [];
gdjs.ImpostazioniCode.GDLivello4Objects1= [];
gdjs.ImpostazioniCode.GDLivello4Objects2= [];
gdjs.ImpostazioniCode.GDLivello4Objects3= [];
gdjs.ImpostazioniCode.GDLivello5Objects1= [];
gdjs.ImpostazioniCode.GDLivello5Objects2= [];
gdjs.ImpostazioniCode.GDLivello5Objects3= [];
gdjs.ImpostazioniCode.GDFal_95249_9595ciao_9595io_9595sono_9595fal_95249Objects1= [];
gdjs.ImpostazioniCode.GDFal_95249_9595ciao_9595io_9595sono_9595fal_95249Objects2= [];
gdjs.ImpostazioniCode.GDFal_95249_9595ciao_9595io_9595sono_9595fal_95249Objects3= [];
gdjs.ImpostazioniCode.GDClassificaObjects1= [];
gdjs.ImpostazioniCode.GDClassificaObjects2= [];
gdjs.ImpostazioniCode.GDClassificaObjects3= [];
gdjs.ImpostazioniCode.GDModalita_9595TempoObjects1= [];
gdjs.ImpostazioniCode.GDModalita_9595TempoObjects2= [];
gdjs.ImpostazioniCode.GDModalita_9595TempoObjects3= [];
gdjs.ImpostazioniCode.GDUnnamedObjects1= [];
gdjs.ImpostazioniCode.GDUnnamedObjects2= [];
gdjs.ImpostazioniCode.GDUnnamedObjects3= [];
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiamiObjects1= [];
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiamiObjects2= [];
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiamiObjects3= [];
gdjs.ImpostazioniCode.GDTopDownTerrain64x64Objects1= [];
gdjs.ImpostazioniCode.GDTopDownTerrain64x64Objects2= [];
gdjs.ImpostazioniCode.GDTopDownTerrain64x64Objects3= [];
gdjs.ImpostazioniCode.GDRiprendiObjects1= [];
gdjs.ImpostazioniCode.GDRiprendiObjects2= [];
gdjs.ImpostazioniCode.GDRiprendiObjects3= [];
gdjs.ImpostazioniCode.GDNomeInputObjects1= [];
gdjs.ImpostazioniCode.GDNomeInputObjects2= [];
gdjs.ImpostazioniCode.GDNomeInputObjects3= [];
gdjs.ImpostazioniCode.GDNomePlayerObjects1= [];
gdjs.ImpostazioniCode.GDNomePlayerObjects2= [];
gdjs.ImpostazioniCode.GDNomePlayerObjects3= [];
gdjs.ImpostazioniCode.GDavantiObjects1= [];
gdjs.ImpostazioniCode.GDavantiObjects2= [];
gdjs.ImpostazioniCode.GDavantiObjects3= [];
gdjs.ImpostazioniCode.GDAvantiObjects1= [];
gdjs.ImpostazioniCode.GDAvantiObjects2= [];
gdjs.ImpostazioniCode.GDAvantiObjects3= [];
gdjs.ImpostazioniCode.GDIndietroObjects1= [];
gdjs.ImpostazioniCode.GDIndietroObjects2= [];
gdjs.ImpostazioniCode.GDIndietroObjects3= [];
gdjs.ImpostazioniCode.GDAspettoObjects1= [];
gdjs.ImpostazioniCode.GDAspettoObjects2= [];
gdjs.ImpostazioniCode.GDAspettoObjects3= [];
gdjs.ImpostazioniCode.GDCosa_9595fa_9595Objects1= [];
gdjs.ImpostazioniCode.GDCosa_9595fa_9595Objects2= [];
gdjs.ImpostazioniCode.GDCosa_9595fa_9595Objects3= [];
gdjs.ImpostazioniCode.GDParti_9595SpecialiObjects1= [];
gdjs.ImpostazioniCode.GDParti_9595SpecialiObjects2= [];
gdjs.ImpostazioniCode.GDParti_9595SpecialiObjects3= [];
gdjs.ImpostazioniCode.GDCuriosit_95224Objects1= [];
gdjs.ImpostazioniCode.GDCuriosit_95224Objects2= [];
gdjs.ImpostazioniCode.GDCuriosit_95224Objects3= [];
gdjs.ImpostazioniCode.GDAttentoObjects1= [];
gdjs.ImpostazioniCode.GDAttentoObjects2= [];
gdjs.ImpostazioniCode.GDAttentoObjects3= [];
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiami7Objects1= [];
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiami7Objects2= [];
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiami7Objects3= [];
gdjs.ImpostazioniCode.GDLeoneObjects1= [];
gdjs.ImpostazioniCode.GDLeoneObjects2= [];
gdjs.ImpostazioniCode.GDLeoneObjects3= [];
gdjs.ImpostazioniCode.GDCoccodrilloObjects1= [];
gdjs.ImpostazioniCode.GDCoccodrilloObjects2= [];
gdjs.ImpostazioniCode.GDCoccodrilloObjects3= [];
gdjs.ImpostazioniCode.GDRinoceronteObjects1= [];
gdjs.ImpostazioniCode.GDRinoceronteObjects2= [];
gdjs.ImpostazioniCode.GDRinoceronteObjects3= [];
gdjs.ImpostazioniCode.GDMangustaObjects1= [];
gdjs.ImpostazioniCode.GDMangustaObjects2= [];
gdjs.ImpostazioniCode.GDMangustaObjects3= [];
gdjs.ImpostazioniCode.GDElefanteObjects1= [];
gdjs.ImpostazioniCode.GDElefanteObjects2= [];
gdjs.ImpostazioniCode.GDElefanteObjects3= [];
gdjs.ImpostazioniCode.GDIenaObjects1= [];
gdjs.ImpostazioniCode.GDIenaObjects2= [];
gdjs.ImpostazioniCode.GDIenaObjects3= [];
gdjs.ImpostazioniCode.GDZebraObjects1= [];
gdjs.ImpostazioniCode.GDZebraObjects2= [];
gdjs.ImpostazioniCode.GDZebraObjects3= [];
gdjs.ImpostazioniCode.GDAvvoltoioObjects1= [];
gdjs.ImpostazioniCode.GDAvvoltoioObjects2= [];
gdjs.ImpostazioniCode.GDAvvoltoioObjects3= [];
gdjs.ImpostazioniCode.GDGhepardoObjects1= [];
gdjs.ImpostazioniCode.GDGhepardoObjects2= [];
gdjs.ImpostazioniCode.GDGhepardoObjects3= [];
gdjs.ImpostazioniCode.GDLeopardoObjects1= [];
gdjs.ImpostazioniCode.GDLeopardoObjects2= [];
gdjs.ImpostazioniCode.GDLeopardoObjects3= [];
gdjs.ImpostazioniCode.GDIppopotamoObjects1= [];
gdjs.ImpostazioniCode.GDIppopotamoObjects2= [];
gdjs.ImpostazioniCode.GDIppopotamoObjects3= [];
gdjs.ImpostazioniCode.GDOriceObjects1= [];
gdjs.ImpostazioniCode.GDOriceObjects2= [];
gdjs.ImpostazioniCode.GDOriceObjects3= [];
gdjs.ImpostazioniCode.GDFacoceroObjects1= [];
gdjs.ImpostazioniCode.GDFacoceroObjects2= [];
gdjs.ImpostazioniCode.GDFacoceroObjects3= [];
gdjs.ImpostazioniCode.GDGnuObjects1= [];
gdjs.ImpostazioniCode.GDGnuObjects2= [];
gdjs.ImpostazioniCode.GDGnuObjects3= [];
gdjs.ImpostazioniCode.GDLupoAfricanoObjects1= [];
gdjs.ImpostazioniCode.GDLupoAfricanoObjects2= [];
gdjs.ImpostazioniCode.GDLupoAfricanoObjects3= [];
gdjs.ImpostazioniCode.GDGiraffaObjects1= [];
gdjs.ImpostazioniCode.GDGiraffaObjects2= [];
gdjs.ImpostazioniCode.GDGiraffaObjects3= [];
gdjs.ImpostazioniCode.GDScacalloStriatoObjects1= [];
gdjs.ImpostazioniCode.GDScacalloStriatoObjects2= [];
gdjs.ImpostazioniCode.GDScacalloStriatoObjects3= [];
gdjs.ImpostazioniCode.GDServalObjects1= [];
gdjs.ImpostazioniCode.GDServalObjects2= [];
gdjs.ImpostazioniCode.GDServalObjects3= [];
gdjs.ImpostazioniCode.GDDik_9595DikObjects1= [];
gdjs.ImpostazioniCode.GDDik_9595DikObjects2= [];
gdjs.ImpostazioniCode.GDDik_9595DikObjects3= [];
gdjs.ImpostazioniCode.GDGazzellaObjects1= [];
gdjs.ImpostazioniCode.GDGazzellaObjects2= [];
gdjs.ImpostazioniCode.GDGazzellaObjects3= [];
gdjs.ImpostazioniCode.GDLicaoneObjects1= [];
gdjs.ImpostazioniCode.GDLicaoneObjects2= [];
gdjs.ImpostazioniCode.GDLicaoneObjects3= [];
gdjs.ImpostazioniCode.GDStruzzoObjects1= [];
gdjs.ImpostazioniCode.GDStruzzoObjects2= [];
gdjs.ImpostazioniCode.GDStruzzoObjects3= [];
gdjs.ImpostazioniCode.GDSerpentarioObjects1= [];
gdjs.ImpostazioniCode.GDSerpentarioObjects2= [];
gdjs.ImpostazioniCode.GDSerpentarioObjects3= [];
gdjs.ImpostazioniCode.GDExplosion3Objects1= [];
gdjs.ImpostazioniCode.GDExplosion3Objects2= [];
gdjs.ImpostazioniCode.GDExplosion3Objects3= [];
gdjs.ImpostazioniCode.GDStarParticleObjects1= [];
gdjs.ImpostazioniCode.GDStarParticleObjects2= [];
gdjs.ImpostazioniCode.GDStarParticleObjects3= [];
gdjs.ImpostazioniCode.GDAvviaObjects1= [];
gdjs.ImpostazioniCode.GDAvviaObjects2= [];
gdjs.ImpostazioniCode.GDAvviaObjects3= [];
gdjs.ImpostazioniCode.GDFalsoObjects1= [];
gdjs.ImpostazioniCode.GDFalsoObjects2= [];
gdjs.ImpostazioniCode.GDFalsoObjects3= [];
gdjs.ImpostazioniCode.GDVeroObjects1= [];
gdjs.ImpostazioniCode.GDVeroObjects2= [];
gdjs.ImpostazioniCode.GDVeroObjects3= [];
gdjs.ImpostazioniCode.GDImpostazioni2Objects1= [];
gdjs.ImpostazioniCode.GDImpostazioni2Objects2= [];
gdjs.ImpostazioniCode.GDImpostazioni2Objects3= [];
gdjs.ImpostazioniCode.GDimpostazioniObjects1= [];
gdjs.ImpostazioniCode.GDimpostazioniObjects2= [];
gdjs.ImpostazioniCode.GDimpostazioniObjects3= [];
gdjs.ImpostazioniCode.GDHomeObjects1= [];
gdjs.ImpostazioniCode.GDHomeObjects2= [];
gdjs.ImpostazioniCode.GDHomeObjects3= [];
gdjs.ImpostazioniCode.GDRetry2Objects1= [];
gdjs.ImpostazioniCode.GDRetry2Objects2= [];
gdjs.ImpostazioniCode.GDRetry2Objects3= [];


gdjs.ImpostazioniCode.eventsList0 = function(runtimeScene) {

{


let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.runtimeScene.sceneJustBegins(runtimeScene);
if (isConditionTrue_0) {
gdjs.copyArray(runtimeScene.getObjects("NomePlayer"), gdjs.ImpostazioniCode.GDNomePlayerObjects2);
gdjs.copyArray(runtimeScene.getObjects("Punteggio"), gdjs.ImpostazioniCode.GDPunteggioObjects2);
gdjs.copyArray(runtimeScene.getObjects("ScreenFade"), gdjs.ImpostazioniCode.GDScreenFadeObjects2);
{for(var i = 0, len = gdjs.ImpostazioniCode.GDScreenFadeObjects2.length ;i < len;++i) {
    gdjs.ImpostazioniCode.GDScreenFadeObjects2[i].getBehavior("Tween").addObjectOpacityTween2("FadeIn", 0, "linear", 1, true);
}
}{gdjs.evtTools.storage.readStringFromJSONFile("Gamedata", runtimeScene.getGame().getVariables().getFromIndex(9).getAsString(), runtimeScene, runtimeScene.getGame().getVariables().getFromIndex(9));
}{runtimeScene.getGame().getVariables().getFromIndex(7).setNumber(runtimeScene.getGame().getVariables().getFromIndex(6).getAsNumber() + runtimeScene.getGame().getVariables().getFromIndex(7).getAsNumber());
}{for(var i = 0, len = gdjs.ImpostazioniCode.GDPunteggioObjects2.length ;i < len;++i) {
    gdjs.ImpostazioniCode.GDPunteggioObjects2[i].getBehavior("Text").setText("Punteggio: " + gdjs.evtTools.common.toString(Math.round(gdjs.evtTools.variable.getVariableNumber(runtimeScene.getGame().getVariables().getFromIndex(7)) * 1 * 10) / 10));
}
}{for(var i = 0, len = gdjs.ImpostazioniCode.GDNomePlayerObjects2.length ;i < len;++i) {
    gdjs.ImpostazioniCode.GDNomePlayerObjects2[i].getBehavior("Text").setText(gdjs.evtTools.variable.getVariableString(runtimeScene.getGame().getVariables().getFromIndex(10)));
}
}}

}


{

gdjs.copyArray(runtimeScene.getObjects("Musica"), gdjs.ImpostazioniCode.GDMusicaObjects2);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
for (var i = 0, k = 0, l = gdjs.ImpostazioniCode.GDMusicaObjects2.length;i<l;++i) {
    if ( gdjs.ImpostazioniCode.GDMusicaObjects2[i].IsBeingDragged((typeof eventsFunctionContext !== 'undefined' ? eventsFunctionContext : undefined)) ) {
        isConditionTrue_0 = true;
        gdjs.ImpostazioniCode.GDMusicaObjects2[k] = gdjs.ImpostazioniCode.GDMusicaObjects2[i];
        ++k;
    }
}
gdjs.ImpostazioniCode.GDMusicaObjects2.length = k;
if (isConditionTrue_0) {
/* Reuse gdjs.ImpostazioniCode.GDMusicaObjects2 */
{runtimeScene.getGame().getVariables().getFromIndex(1).setNumber((( gdjs.ImpostazioniCode.GDMusicaObjects2.length === 0 ) ? 0 :gdjs.ImpostazioniCode.GDMusicaObjects2[0].Value((typeof eventsFunctionContext !== 'undefined' ? eventsFunctionContext : undefined))));
}{gdjs.evtTools.sound.setSoundOnChannelVolume(runtimeScene, 2, runtimeScene.getGame().getVariables().getFromIndex(1).getAsNumber());
}}

}


{

gdjs.copyArray(runtimeScene.getObjects("EFFETTI"), gdjs.ImpostazioniCode.GDEFFETTIObjects2);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
for (var i = 0, k = 0, l = gdjs.ImpostazioniCode.GDEFFETTIObjects2.length;i<l;++i) {
    if ( gdjs.ImpostazioniCode.GDEFFETTIObjects2[i].IsBeingDragged((typeof eventsFunctionContext !== 'undefined' ? eventsFunctionContext : undefined)) ) {
        isConditionTrue_0 = true;
        gdjs.ImpostazioniCode.GDEFFETTIObjects2[k] = gdjs.ImpostazioniCode.GDEFFETTIObjects2[i];
        ++k;
    }
}
gdjs.ImpostazioniCode.GDEFFETTIObjects2.length = k;
if (isConditionTrue_0) {
/* Reuse gdjs.ImpostazioniCode.GDEFFETTIObjects2 */
{runtimeScene.getGame().getVariables().getFromIndex(2).setNumber((( gdjs.ImpostazioniCode.GDEFFETTIObjects2.length === 0 ) ? 0 :gdjs.ImpostazioniCode.GDEFFETTIObjects2[0].Value((typeof eventsFunctionContext !== 'undefined' ? eventsFunctionContext : undefined))));
}{gdjs.evtTools.sound.setSoundOnChannelVolume(runtimeScene, 1, runtimeScene.getGame().getVariables().getFromIndex(2).getAsNumber());
}}

}


{

gdjs.copyArray(runtimeScene.getObjects("Retry2"), gdjs.ImpostazioniCode.GDRetry2Objects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
for (var i = 0, k = 0, l = gdjs.ImpostazioniCode.GDRetry2Objects1.length;i<l;++i) {
    if ( gdjs.ImpostazioniCode.GDRetry2Objects1[i].IsClicked((typeof eventsFunctionContext !== 'undefined' ? eventsFunctionContext : undefined)) ) {
        isConditionTrue_0 = true;
        gdjs.ImpostazioniCode.GDRetry2Objects1[k] = gdjs.ImpostazioniCode.GDRetry2Objects1[i];
        ++k;
    }
}
gdjs.ImpostazioniCode.GDRetry2Objects1.length = k;
if (isConditionTrue_0) {
{gdjs.evtTools.runtimeScene.popScene(runtimeScene);
}}

}


};gdjs.ImpostazioniCode.eventsList1 = function(runtimeScene) {

{


gdjs.ImpostazioniCode.eventsList0(runtimeScene);
}


};

gdjs.ImpostazioniCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();

gdjs.ImpostazioniCode.GDPositionPlaceholderObjects1.length = 0;
gdjs.ImpostazioniCode.GDPositionPlaceholderObjects2.length = 0;
gdjs.ImpostazioniCode.GDPositionPlaceholderObjects3.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects1.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects2.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects3.length = 0;
gdjs.ImpostazioniCode.GDScreenFadeObjects1.length = 0;
gdjs.ImpostazioniCode.GDScreenFadeObjects2.length = 0;
gdjs.ImpostazioniCode.GDScreenFadeObjects3.length = 0;
gdjs.ImpostazioniCode.GDCollezione_9595CartaObjects1.length = 0;
gdjs.ImpostazioniCode.GDCollezione_9595CartaObjects2.length = 0;
gdjs.ImpostazioniCode.GDCollezione_9595CartaObjects3.length = 0;
gdjs.ImpostazioniCode.GDNuovo_9595GiocoObjects1.length = 0;
gdjs.ImpostazioniCode.GDNuovo_9595GiocoObjects2.length = 0;
gdjs.ImpostazioniCode.GDNuovo_9595GiocoObjects3.length = 0;
gdjs.ImpostazioniCode.GDModalit_95224_9595a_9595tempoObjects1.length = 0;
gdjs.ImpostazioniCode.GDModalit_95224_9595a_9595tempoObjects2.length = 0;
gdjs.ImpostazioniCode.GDModalit_95224_9595a_9595tempoObjects3.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSpriteObjects1.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSpriteObjects2.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSpriteObjects3.length = 0;
gdjs.ImpostazioniCode.GDGioca_9595e_9595imparaObjects1.length = 0;
gdjs.ImpostazioniCode.GDGioca_9595e_9595imparaObjects2.length = 0;
gdjs.ImpostazioniCode.GDGioca_9595e_9595imparaObjects3.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSprite2Objects1.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSprite2Objects2.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSprite2Objects3.length = 0;
gdjs.ImpostazioniCode.GDMusicaObjects1.length = 0;
gdjs.ImpostazioniCode.GDMusicaObjects2.length = 0;
gdjs.ImpostazioniCode.GDMusicaObjects3.length = 0;
gdjs.ImpostazioniCode.GDEFFETTIObjects1.length = 0;
gdjs.ImpostazioniCode.GDEFFETTIObjects2.length = 0;
gdjs.ImpostazioniCode.GDEFFETTIObjects3.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595musicaObjects1.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595musicaObjects2.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595musicaObjects3.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595EffettiObjects1.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595EffettiObjects2.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595EffettiObjects3.length = 0;
gdjs.ImpostazioniCode.GDMuteObjects1.length = 0;
gdjs.ImpostazioniCode.GDMuteObjects2.length = 0;
gdjs.ImpostazioniCode.GDMuteObjects3.length = 0;
gdjs.ImpostazioniCode.GDRiprovaObjects1.length = 0;
gdjs.ImpostazioniCode.GDRiprovaObjects2.length = 0;
gdjs.ImpostazioniCode.GDRiprovaObjects3.length = 0;
gdjs.ImpostazioniCode.GDMen_95249Objects1.length = 0;
gdjs.ImpostazioniCode.GDMen_95249Objects2.length = 0;
gdjs.ImpostazioniCode.GDMen_95249Objects3.length = 0;
gdjs.ImpostazioniCode.GDRiprendi8Objects1.length = 0;
gdjs.ImpostazioniCode.GDRiprendi8Objects2.length = 0;
gdjs.ImpostazioniCode.GDRiprendi8Objects3.length = 0;
gdjs.ImpostazioniCode.GDPausaObjects1.length = 0;
gdjs.ImpostazioniCode.GDPausaObjects2.length = 0;
gdjs.ImpostazioniCode.GDPausaObjects3.length = 0;
gdjs.ImpostazioniCode.GDOKObjects1.length = 0;
gdjs.ImpostazioniCode.GDOKObjects2.length = 0;
gdjs.ImpostazioniCode.GDOKObjects3.length = 0;
gdjs.ImpostazioniCode.GDInserimento_9595nomeObjects1.length = 0;
gdjs.ImpostazioniCode.GDInserimento_9595nomeObjects2.length = 0;
gdjs.ImpostazioniCode.GDInserimento_9595nomeObjects3.length = 0;
gdjs.ImpostazioniCode.GDCiaoObjects1.length = 0;
gdjs.ImpostazioniCode.GDCiaoObjects2.length = 0;
gdjs.ImpostazioniCode.GDCiaoObjects3.length = 0;
gdjs.ImpostazioniCode.GDLivelloSucessivo3Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivelloSucessivo3Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivelloSucessivo3Objects3.length = 0;
gdjs.ImpostazioniCode.GDTitoloObjects1.length = 0;
gdjs.ImpostazioniCode.GDTitoloObjects2.length = 0;
gdjs.ImpostazioniCode.GDTitoloObjects3.length = 0;
gdjs.ImpostazioniCode.GDBlackBackgroundObjects1.length = 0;
gdjs.ImpostazioniCode.GDBlackBackgroundObjects2.length = 0;
gdjs.ImpostazioniCode.GDBlackBackgroundObjects3.length = 0;
gdjs.ImpostazioniCode.GDSelectionObjects1.length = 0;
gdjs.ImpostazioniCode.GDSelectionObjects2.length = 0;
gdjs.ImpostazioniCode.GDSelectionObjects3.length = 0;
gdjs.ImpostazioniCode.GDPunteggioObjects1.length = 0;
gdjs.ImpostazioniCode.GDPunteggioObjects2.length = 0;
gdjs.ImpostazioniCode.GDPunteggioObjects3.length = 0;
gdjs.ImpostazioniCode.GDTempoTestoObjects1.length = 0;
gdjs.ImpostazioniCode.GDTempoTestoObjects2.length = 0;
gdjs.ImpostazioniCode.GDTempoTestoObjects3.length = 0;
gdjs.ImpostazioniCode.GDCoppieObjects1.length = 0;
gdjs.ImpostazioniCode.GDCoppieObjects2.length = 0;
gdjs.ImpostazioniCode.GDCoppieObjects3.length = 0;
gdjs.ImpostazioniCode.GDLivello6Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello6Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello6Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello_95957Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello_95957Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello_95957Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello1Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello1Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello1Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello2Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello2Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello2Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello3Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello3Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello3Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello4Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello4Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello4Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello5Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello5Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello5Objects3.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595ciao_9595io_9595sono_9595fal_95249Objects1.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595ciao_9595io_9595sono_9595fal_95249Objects2.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595ciao_9595io_9595sono_9595fal_95249Objects3.length = 0;
gdjs.ImpostazioniCode.GDClassificaObjects1.length = 0;
gdjs.ImpostazioniCode.GDClassificaObjects2.length = 0;
gdjs.ImpostazioniCode.GDClassificaObjects3.length = 0;
gdjs.ImpostazioniCode.GDModalita_9595TempoObjects1.length = 0;
gdjs.ImpostazioniCode.GDModalita_9595TempoObjects2.length = 0;
gdjs.ImpostazioniCode.GDModalita_9595TempoObjects3.length = 0;
gdjs.ImpostazioniCode.GDUnnamedObjects1.length = 0;
gdjs.ImpostazioniCode.GDUnnamedObjects2.length = 0;
gdjs.ImpostazioniCode.GDUnnamedObjects3.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiamiObjects1.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiamiObjects2.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiamiObjects3.length = 0;
gdjs.ImpostazioniCode.GDTopDownTerrain64x64Objects1.length = 0;
gdjs.ImpostazioniCode.GDTopDownTerrain64x64Objects2.length = 0;
gdjs.ImpostazioniCode.GDTopDownTerrain64x64Objects3.length = 0;
gdjs.ImpostazioniCode.GDRiprendiObjects1.length = 0;
gdjs.ImpostazioniCode.GDRiprendiObjects2.length = 0;
gdjs.ImpostazioniCode.GDRiprendiObjects3.length = 0;
gdjs.ImpostazioniCode.GDNomeInputObjects1.length = 0;
gdjs.ImpostazioniCode.GDNomeInputObjects2.length = 0;
gdjs.ImpostazioniCode.GDNomeInputObjects3.length = 0;
gdjs.ImpostazioniCode.GDNomePlayerObjects1.length = 0;
gdjs.ImpostazioniCode.GDNomePlayerObjects2.length = 0;
gdjs.ImpostazioniCode.GDNomePlayerObjects3.length = 0;
gdjs.ImpostazioniCode.GDavantiObjects1.length = 0;
gdjs.ImpostazioniCode.GDavantiObjects2.length = 0;
gdjs.ImpostazioniCode.GDavantiObjects3.length = 0;
gdjs.ImpostazioniCode.GDAvantiObjects1.length = 0;
gdjs.ImpostazioniCode.GDAvantiObjects2.length = 0;
gdjs.ImpostazioniCode.GDAvantiObjects3.length = 0;
gdjs.ImpostazioniCode.GDIndietroObjects1.length = 0;
gdjs.ImpostazioniCode.GDIndietroObjects2.length = 0;
gdjs.ImpostazioniCode.GDIndietroObjects3.length = 0;
gdjs.ImpostazioniCode.GDAspettoObjects1.length = 0;
gdjs.ImpostazioniCode.GDAspettoObjects2.length = 0;
gdjs.ImpostazioniCode.GDAspettoObjects3.length = 0;
gdjs.ImpostazioniCode.GDCosa_9595fa_9595Objects1.length = 0;
gdjs.ImpostazioniCode.GDCosa_9595fa_9595Objects2.length = 0;
gdjs.ImpostazioniCode.GDCosa_9595fa_9595Objects3.length = 0;
gdjs.ImpostazioniCode.GDParti_9595SpecialiObjects1.length = 0;
gdjs.ImpostazioniCode.GDParti_9595SpecialiObjects2.length = 0;
gdjs.ImpostazioniCode.GDParti_9595SpecialiObjects3.length = 0;
gdjs.ImpostazioniCode.GDCuriosit_95224Objects1.length = 0;
gdjs.ImpostazioniCode.GDCuriosit_95224Objects2.length = 0;
gdjs.ImpostazioniCode.GDCuriosit_95224Objects3.length = 0;
gdjs.ImpostazioniCode.GDAttentoObjects1.length = 0;
gdjs.ImpostazioniCode.GDAttentoObjects2.length = 0;
gdjs.ImpostazioniCode.GDAttentoObjects3.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiami7Objects1.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiami7Objects2.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiami7Objects3.length = 0;
gdjs.ImpostazioniCode.GDLeoneObjects1.length = 0;
gdjs.ImpostazioniCode.GDLeoneObjects2.length = 0;
gdjs.ImpostazioniCode.GDLeoneObjects3.length = 0;
gdjs.ImpostazioniCode.GDCoccodrilloObjects1.length = 0;
gdjs.ImpostazioniCode.GDCoccodrilloObjects2.length = 0;
gdjs.ImpostazioniCode.GDCoccodrilloObjects3.length = 0;
gdjs.ImpostazioniCode.GDRinoceronteObjects1.length = 0;
gdjs.ImpostazioniCode.GDRinoceronteObjects2.length = 0;
gdjs.ImpostazioniCode.GDRinoceronteObjects3.length = 0;
gdjs.ImpostazioniCode.GDMangustaObjects1.length = 0;
gdjs.ImpostazioniCode.GDMangustaObjects2.length = 0;
gdjs.ImpostazioniCode.GDMangustaObjects3.length = 0;
gdjs.ImpostazioniCode.GDElefanteObjects1.length = 0;
gdjs.ImpostazioniCode.GDElefanteObjects2.length = 0;
gdjs.ImpostazioniCode.GDElefanteObjects3.length = 0;
gdjs.ImpostazioniCode.GDIenaObjects1.length = 0;
gdjs.ImpostazioniCode.GDIenaObjects2.length = 0;
gdjs.ImpostazioniCode.GDIenaObjects3.length = 0;
gdjs.ImpostazioniCode.GDZebraObjects1.length = 0;
gdjs.ImpostazioniCode.GDZebraObjects2.length = 0;
gdjs.ImpostazioniCode.GDZebraObjects3.length = 0;
gdjs.ImpostazioniCode.GDAvvoltoioObjects1.length = 0;
gdjs.ImpostazioniCode.GDAvvoltoioObjects2.length = 0;
gdjs.ImpostazioniCode.GDAvvoltoioObjects3.length = 0;
gdjs.ImpostazioniCode.GDGhepardoObjects1.length = 0;
gdjs.ImpostazioniCode.GDGhepardoObjects2.length = 0;
gdjs.ImpostazioniCode.GDGhepardoObjects3.length = 0;
gdjs.ImpostazioniCode.GDLeopardoObjects1.length = 0;
gdjs.ImpostazioniCode.GDLeopardoObjects2.length = 0;
gdjs.ImpostazioniCode.GDLeopardoObjects3.length = 0;
gdjs.ImpostazioniCode.GDIppopotamoObjects1.length = 0;
gdjs.ImpostazioniCode.GDIppopotamoObjects2.length = 0;
gdjs.ImpostazioniCode.GDIppopotamoObjects3.length = 0;
gdjs.ImpostazioniCode.GDOriceObjects1.length = 0;
gdjs.ImpostazioniCode.GDOriceObjects2.length = 0;
gdjs.ImpostazioniCode.GDOriceObjects3.length = 0;
gdjs.ImpostazioniCode.GDFacoceroObjects1.length = 0;
gdjs.ImpostazioniCode.GDFacoceroObjects2.length = 0;
gdjs.ImpostazioniCode.GDFacoceroObjects3.length = 0;
gdjs.ImpostazioniCode.GDGnuObjects1.length = 0;
gdjs.ImpostazioniCode.GDGnuObjects2.length = 0;
gdjs.ImpostazioniCode.GDGnuObjects3.length = 0;
gdjs.ImpostazioniCode.GDLupoAfricanoObjects1.length = 0;
gdjs.ImpostazioniCode.GDLupoAfricanoObjects2.length = 0;
gdjs.ImpostazioniCode.GDLupoAfricanoObjects3.length = 0;
gdjs.ImpostazioniCode.GDGiraffaObjects1.length = 0;
gdjs.ImpostazioniCode.GDGiraffaObjects2.length = 0;
gdjs.ImpostazioniCode.GDGiraffaObjects3.length = 0;
gdjs.ImpostazioniCode.GDScacalloStriatoObjects1.length = 0;
gdjs.ImpostazioniCode.GDScacalloStriatoObjects2.length = 0;
gdjs.ImpostazioniCode.GDScacalloStriatoObjects3.length = 0;
gdjs.ImpostazioniCode.GDServalObjects1.length = 0;
gdjs.ImpostazioniCode.GDServalObjects2.length = 0;
gdjs.ImpostazioniCode.GDServalObjects3.length = 0;
gdjs.ImpostazioniCode.GDDik_9595DikObjects1.length = 0;
gdjs.ImpostazioniCode.GDDik_9595DikObjects2.length = 0;
gdjs.ImpostazioniCode.GDDik_9595DikObjects3.length = 0;
gdjs.ImpostazioniCode.GDGazzellaObjects1.length = 0;
gdjs.ImpostazioniCode.GDGazzellaObjects2.length = 0;
gdjs.ImpostazioniCode.GDGazzellaObjects3.length = 0;
gdjs.ImpostazioniCode.GDLicaoneObjects1.length = 0;
gdjs.ImpostazioniCode.GDLicaoneObjects2.length = 0;
gdjs.ImpostazioniCode.GDLicaoneObjects3.length = 0;
gdjs.ImpostazioniCode.GDStruzzoObjects1.length = 0;
gdjs.ImpostazioniCode.GDStruzzoObjects2.length = 0;
gdjs.ImpostazioniCode.GDStruzzoObjects3.length = 0;
gdjs.ImpostazioniCode.GDSerpentarioObjects1.length = 0;
gdjs.ImpostazioniCode.GDSerpentarioObjects2.length = 0;
gdjs.ImpostazioniCode.GDSerpentarioObjects3.length = 0;
gdjs.ImpostazioniCode.GDExplosion3Objects1.length = 0;
gdjs.ImpostazioniCode.GDExplosion3Objects2.length = 0;
gdjs.ImpostazioniCode.GDExplosion3Objects3.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects1.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects2.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects3.length = 0;
gdjs.ImpostazioniCode.GDAvviaObjects1.length = 0;
gdjs.ImpostazioniCode.GDAvviaObjects2.length = 0;
gdjs.ImpostazioniCode.GDAvviaObjects3.length = 0;
gdjs.ImpostazioniCode.GDFalsoObjects1.length = 0;
gdjs.ImpostazioniCode.GDFalsoObjects2.length = 0;
gdjs.ImpostazioniCode.GDFalsoObjects3.length = 0;
gdjs.ImpostazioniCode.GDVeroObjects1.length = 0;
gdjs.ImpostazioniCode.GDVeroObjects2.length = 0;
gdjs.ImpostazioniCode.GDVeroObjects3.length = 0;
gdjs.ImpostazioniCode.GDImpostazioni2Objects1.length = 0;
gdjs.ImpostazioniCode.GDImpostazioni2Objects2.length = 0;
gdjs.ImpostazioniCode.GDImpostazioni2Objects3.length = 0;
gdjs.ImpostazioniCode.GDimpostazioniObjects1.length = 0;
gdjs.ImpostazioniCode.GDimpostazioniObjects2.length = 0;
gdjs.ImpostazioniCode.GDimpostazioniObjects3.length = 0;
gdjs.ImpostazioniCode.GDHomeObjects1.length = 0;
gdjs.ImpostazioniCode.GDHomeObjects2.length = 0;
gdjs.ImpostazioniCode.GDHomeObjects3.length = 0;
gdjs.ImpostazioniCode.GDRetry2Objects1.length = 0;
gdjs.ImpostazioniCode.GDRetry2Objects2.length = 0;
gdjs.ImpostazioniCode.GDRetry2Objects3.length = 0;

gdjs.ImpostazioniCode.eventsList1(runtimeScene);
gdjs.ImpostazioniCode.GDPositionPlaceholderObjects1.length = 0;
gdjs.ImpostazioniCode.GDPositionPlaceholderObjects2.length = 0;
gdjs.ImpostazioniCode.GDPositionPlaceholderObjects3.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects1.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects2.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects3.length = 0;
gdjs.ImpostazioniCode.GDScreenFadeObjects1.length = 0;
gdjs.ImpostazioniCode.GDScreenFadeObjects2.length = 0;
gdjs.ImpostazioniCode.GDScreenFadeObjects3.length = 0;
gdjs.ImpostazioniCode.GDCollezione_9595CartaObjects1.length = 0;
gdjs.ImpostazioniCode.GDCollezione_9595CartaObjects2.length = 0;
gdjs.ImpostazioniCode.GDCollezione_9595CartaObjects3.length = 0;
gdjs.ImpostazioniCode.GDNuovo_9595GiocoObjects1.length = 0;
gdjs.ImpostazioniCode.GDNuovo_9595GiocoObjects2.length = 0;
gdjs.ImpostazioniCode.GDNuovo_9595GiocoObjects3.length = 0;
gdjs.ImpostazioniCode.GDModalit_95224_9595a_9595tempoObjects1.length = 0;
gdjs.ImpostazioniCode.GDModalit_95224_9595a_9595tempoObjects2.length = 0;
gdjs.ImpostazioniCode.GDModalit_95224_9595a_9595tempoObjects3.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSpriteObjects1.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSpriteObjects2.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSpriteObjects3.length = 0;
gdjs.ImpostazioniCode.GDGioca_9595e_9595imparaObjects1.length = 0;
gdjs.ImpostazioniCode.GDGioca_9595e_9595imparaObjects2.length = 0;
gdjs.ImpostazioniCode.GDGioca_9595e_9595imparaObjects3.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSprite2Objects1.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSprite2Objects2.length = 0;
gdjs.ImpostazioniCode.GDNewTiledSprite2Objects3.length = 0;
gdjs.ImpostazioniCode.GDMusicaObjects1.length = 0;
gdjs.ImpostazioniCode.GDMusicaObjects2.length = 0;
gdjs.ImpostazioniCode.GDMusicaObjects3.length = 0;
gdjs.ImpostazioniCode.GDEFFETTIObjects1.length = 0;
gdjs.ImpostazioniCode.GDEFFETTIObjects2.length = 0;
gdjs.ImpostazioniCode.GDEFFETTIObjects3.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595musicaObjects1.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595musicaObjects2.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595musicaObjects3.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595EffettiObjects1.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595EffettiObjects2.length = 0;
gdjs.ImpostazioniCode.GDVolume_9595EffettiObjects3.length = 0;
gdjs.ImpostazioniCode.GDMuteObjects1.length = 0;
gdjs.ImpostazioniCode.GDMuteObjects2.length = 0;
gdjs.ImpostazioniCode.GDMuteObjects3.length = 0;
gdjs.ImpostazioniCode.GDRiprovaObjects1.length = 0;
gdjs.ImpostazioniCode.GDRiprovaObjects2.length = 0;
gdjs.ImpostazioniCode.GDRiprovaObjects3.length = 0;
gdjs.ImpostazioniCode.GDMen_95249Objects1.length = 0;
gdjs.ImpostazioniCode.GDMen_95249Objects2.length = 0;
gdjs.ImpostazioniCode.GDMen_95249Objects3.length = 0;
gdjs.ImpostazioniCode.GDRiprendi8Objects1.length = 0;
gdjs.ImpostazioniCode.GDRiprendi8Objects2.length = 0;
gdjs.ImpostazioniCode.GDRiprendi8Objects3.length = 0;
gdjs.ImpostazioniCode.GDPausaObjects1.length = 0;
gdjs.ImpostazioniCode.GDPausaObjects2.length = 0;
gdjs.ImpostazioniCode.GDPausaObjects3.length = 0;
gdjs.ImpostazioniCode.GDOKObjects1.length = 0;
gdjs.ImpostazioniCode.GDOKObjects2.length = 0;
gdjs.ImpostazioniCode.GDOKObjects3.length = 0;
gdjs.ImpostazioniCode.GDInserimento_9595nomeObjects1.length = 0;
gdjs.ImpostazioniCode.GDInserimento_9595nomeObjects2.length = 0;
gdjs.ImpostazioniCode.GDInserimento_9595nomeObjects3.length = 0;
gdjs.ImpostazioniCode.GDCiaoObjects1.length = 0;
gdjs.ImpostazioniCode.GDCiaoObjects2.length = 0;
gdjs.ImpostazioniCode.GDCiaoObjects3.length = 0;
gdjs.ImpostazioniCode.GDLivelloSucessivo3Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivelloSucessivo3Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivelloSucessivo3Objects3.length = 0;
gdjs.ImpostazioniCode.GDTitoloObjects1.length = 0;
gdjs.ImpostazioniCode.GDTitoloObjects2.length = 0;
gdjs.ImpostazioniCode.GDTitoloObjects3.length = 0;
gdjs.ImpostazioniCode.GDBlackBackgroundObjects1.length = 0;
gdjs.ImpostazioniCode.GDBlackBackgroundObjects2.length = 0;
gdjs.ImpostazioniCode.GDBlackBackgroundObjects3.length = 0;
gdjs.ImpostazioniCode.GDSelectionObjects1.length = 0;
gdjs.ImpostazioniCode.GDSelectionObjects2.length = 0;
gdjs.ImpostazioniCode.GDSelectionObjects3.length = 0;
gdjs.ImpostazioniCode.GDPunteggioObjects1.length = 0;
gdjs.ImpostazioniCode.GDPunteggioObjects2.length = 0;
gdjs.ImpostazioniCode.GDPunteggioObjects3.length = 0;
gdjs.ImpostazioniCode.GDTempoTestoObjects1.length = 0;
gdjs.ImpostazioniCode.GDTempoTestoObjects2.length = 0;
gdjs.ImpostazioniCode.GDTempoTestoObjects3.length = 0;
gdjs.ImpostazioniCode.GDCoppieObjects1.length = 0;
gdjs.ImpostazioniCode.GDCoppieObjects2.length = 0;
gdjs.ImpostazioniCode.GDCoppieObjects3.length = 0;
gdjs.ImpostazioniCode.GDLivello6Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello6Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello6Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello_95957Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello_95957Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello_95957Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello1Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello1Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello1Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello2Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello2Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello2Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello3Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello3Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello3Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello4Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello4Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello4Objects3.length = 0;
gdjs.ImpostazioniCode.GDLivello5Objects1.length = 0;
gdjs.ImpostazioniCode.GDLivello5Objects2.length = 0;
gdjs.ImpostazioniCode.GDLivello5Objects3.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595ciao_9595io_9595sono_9595fal_95249Objects1.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595ciao_9595io_9595sono_9595fal_95249Objects2.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595ciao_9595io_9595sono_9595fal_95249Objects3.length = 0;
gdjs.ImpostazioniCode.GDClassificaObjects1.length = 0;
gdjs.ImpostazioniCode.GDClassificaObjects2.length = 0;
gdjs.ImpostazioniCode.GDClassificaObjects3.length = 0;
gdjs.ImpostazioniCode.GDModalita_9595TempoObjects1.length = 0;
gdjs.ImpostazioniCode.GDModalita_9595TempoObjects2.length = 0;
gdjs.ImpostazioniCode.GDModalita_9595TempoObjects3.length = 0;
gdjs.ImpostazioniCode.GDUnnamedObjects1.length = 0;
gdjs.ImpostazioniCode.GDUnnamedObjects2.length = 0;
gdjs.ImpostazioniCode.GDUnnamedObjects3.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiamiObjects1.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiamiObjects2.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiamiObjects3.length = 0;
gdjs.ImpostazioniCode.GDTopDownTerrain64x64Objects1.length = 0;
gdjs.ImpostazioniCode.GDTopDownTerrain64x64Objects2.length = 0;
gdjs.ImpostazioniCode.GDTopDownTerrain64x64Objects3.length = 0;
gdjs.ImpostazioniCode.GDRiprendiObjects1.length = 0;
gdjs.ImpostazioniCode.GDRiprendiObjects2.length = 0;
gdjs.ImpostazioniCode.GDRiprendiObjects3.length = 0;
gdjs.ImpostazioniCode.GDNomeInputObjects1.length = 0;
gdjs.ImpostazioniCode.GDNomeInputObjects2.length = 0;
gdjs.ImpostazioniCode.GDNomeInputObjects3.length = 0;
gdjs.ImpostazioniCode.GDNomePlayerObjects1.length = 0;
gdjs.ImpostazioniCode.GDNomePlayerObjects2.length = 0;
gdjs.ImpostazioniCode.GDNomePlayerObjects3.length = 0;
gdjs.ImpostazioniCode.GDavantiObjects1.length = 0;
gdjs.ImpostazioniCode.GDavantiObjects2.length = 0;
gdjs.ImpostazioniCode.GDavantiObjects3.length = 0;
gdjs.ImpostazioniCode.GDAvantiObjects1.length = 0;
gdjs.ImpostazioniCode.GDAvantiObjects2.length = 0;
gdjs.ImpostazioniCode.GDAvantiObjects3.length = 0;
gdjs.ImpostazioniCode.GDIndietroObjects1.length = 0;
gdjs.ImpostazioniCode.GDIndietroObjects2.length = 0;
gdjs.ImpostazioniCode.GDIndietroObjects3.length = 0;
gdjs.ImpostazioniCode.GDAspettoObjects1.length = 0;
gdjs.ImpostazioniCode.GDAspettoObjects2.length = 0;
gdjs.ImpostazioniCode.GDAspettoObjects3.length = 0;
gdjs.ImpostazioniCode.GDCosa_9595fa_9595Objects1.length = 0;
gdjs.ImpostazioniCode.GDCosa_9595fa_9595Objects2.length = 0;
gdjs.ImpostazioniCode.GDCosa_9595fa_9595Objects3.length = 0;
gdjs.ImpostazioniCode.GDParti_9595SpecialiObjects1.length = 0;
gdjs.ImpostazioniCode.GDParti_9595SpecialiObjects2.length = 0;
gdjs.ImpostazioniCode.GDParti_9595SpecialiObjects3.length = 0;
gdjs.ImpostazioniCode.GDCuriosit_95224Objects1.length = 0;
gdjs.ImpostazioniCode.GDCuriosit_95224Objects2.length = 0;
gdjs.ImpostazioniCode.GDCuriosit_95224Objects3.length = 0;
gdjs.ImpostazioniCode.GDAttentoObjects1.length = 0;
gdjs.ImpostazioniCode.GDAttentoObjects2.length = 0;
gdjs.ImpostazioniCode.GDAttentoObjects3.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiami7Objects1.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiami7Objects2.length = 0;
gdjs.ImpostazioniCode.GDFal_95249_9595Tu_9595come_9595ti_9595chiami7Objects3.length = 0;
gdjs.ImpostazioniCode.GDLeoneObjects1.length = 0;
gdjs.ImpostazioniCode.GDLeoneObjects2.length = 0;
gdjs.ImpostazioniCode.GDLeoneObjects3.length = 0;
gdjs.ImpostazioniCode.GDCoccodrilloObjects1.length = 0;
gdjs.ImpostazioniCode.GDCoccodrilloObjects2.length = 0;
gdjs.ImpostazioniCode.GDCoccodrilloObjects3.length = 0;
gdjs.ImpostazioniCode.GDRinoceronteObjects1.length = 0;
gdjs.ImpostazioniCode.GDRinoceronteObjects2.length = 0;
gdjs.ImpostazioniCode.GDRinoceronteObjects3.length = 0;
gdjs.ImpostazioniCode.GDMangustaObjects1.length = 0;
gdjs.ImpostazioniCode.GDMangustaObjects2.length = 0;
gdjs.ImpostazioniCode.GDMangustaObjects3.length = 0;
gdjs.ImpostazioniCode.GDElefanteObjects1.length = 0;
gdjs.ImpostazioniCode.GDElefanteObjects2.length = 0;
gdjs.ImpostazioniCode.GDElefanteObjects3.length = 0;
gdjs.ImpostazioniCode.GDIenaObjects1.length = 0;
gdjs.ImpostazioniCode.GDIenaObjects2.length = 0;
gdjs.ImpostazioniCode.GDIenaObjects3.length = 0;
gdjs.ImpostazioniCode.GDZebraObjects1.length = 0;
gdjs.ImpostazioniCode.GDZebraObjects2.length = 0;
gdjs.ImpostazioniCode.GDZebraObjects3.length = 0;
gdjs.ImpostazioniCode.GDAvvoltoioObjects1.length = 0;
gdjs.ImpostazioniCode.GDAvvoltoioObjects2.length = 0;
gdjs.ImpostazioniCode.GDAvvoltoioObjects3.length = 0;
gdjs.ImpostazioniCode.GDGhepardoObjects1.length = 0;
gdjs.ImpostazioniCode.GDGhepardoObjects2.length = 0;
gdjs.ImpostazioniCode.GDGhepardoObjects3.length = 0;
gdjs.ImpostazioniCode.GDLeopardoObjects1.length = 0;
gdjs.ImpostazioniCode.GDLeopardoObjects2.length = 0;
gdjs.ImpostazioniCode.GDLeopardoObjects3.length = 0;
gdjs.ImpostazioniCode.GDIppopotamoObjects1.length = 0;
gdjs.ImpostazioniCode.GDIppopotamoObjects2.length = 0;
gdjs.ImpostazioniCode.GDIppopotamoObjects3.length = 0;
gdjs.ImpostazioniCode.GDOriceObjects1.length = 0;
gdjs.ImpostazioniCode.GDOriceObjects2.length = 0;
gdjs.ImpostazioniCode.GDOriceObjects3.length = 0;
gdjs.ImpostazioniCode.GDFacoceroObjects1.length = 0;
gdjs.ImpostazioniCode.GDFacoceroObjects2.length = 0;
gdjs.ImpostazioniCode.GDFacoceroObjects3.length = 0;
gdjs.ImpostazioniCode.GDGnuObjects1.length = 0;
gdjs.ImpostazioniCode.GDGnuObjects2.length = 0;
gdjs.ImpostazioniCode.GDGnuObjects3.length = 0;
gdjs.ImpostazioniCode.GDLupoAfricanoObjects1.length = 0;
gdjs.ImpostazioniCode.GDLupoAfricanoObjects2.length = 0;
gdjs.ImpostazioniCode.GDLupoAfricanoObjects3.length = 0;
gdjs.ImpostazioniCode.GDGiraffaObjects1.length = 0;
gdjs.ImpostazioniCode.GDGiraffaObjects2.length = 0;
gdjs.ImpostazioniCode.GDGiraffaObjects3.length = 0;
gdjs.ImpostazioniCode.GDScacalloStriatoObjects1.length = 0;
gdjs.ImpostazioniCode.GDScacalloStriatoObjects2.length = 0;
gdjs.ImpostazioniCode.GDScacalloStriatoObjects3.length = 0;
gdjs.ImpostazioniCode.GDServalObjects1.length = 0;
gdjs.ImpostazioniCode.GDServalObjects2.length = 0;
gdjs.ImpostazioniCode.GDServalObjects3.length = 0;
gdjs.ImpostazioniCode.GDDik_9595DikObjects1.length = 0;
gdjs.ImpostazioniCode.GDDik_9595DikObjects2.length = 0;
gdjs.ImpostazioniCode.GDDik_9595DikObjects3.length = 0;
gdjs.ImpostazioniCode.GDGazzellaObjects1.length = 0;
gdjs.ImpostazioniCode.GDGazzellaObjects2.length = 0;
gdjs.ImpostazioniCode.GDGazzellaObjects3.length = 0;
gdjs.ImpostazioniCode.GDLicaoneObjects1.length = 0;
gdjs.ImpostazioniCode.GDLicaoneObjects2.length = 0;
gdjs.ImpostazioniCode.GDLicaoneObjects3.length = 0;
gdjs.ImpostazioniCode.GDStruzzoObjects1.length = 0;
gdjs.ImpostazioniCode.GDStruzzoObjects2.length = 0;
gdjs.ImpostazioniCode.GDStruzzoObjects3.length = 0;
gdjs.ImpostazioniCode.GDSerpentarioObjects1.length = 0;
gdjs.ImpostazioniCode.GDSerpentarioObjects2.length = 0;
gdjs.ImpostazioniCode.GDSerpentarioObjects3.length = 0;
gdjs.ImpostazioniCode.GDExplosion3Objects1.length = 0;
gdjs.ImpostazioniCode.GDExplosion3Objects2.length = 0;
gdjs.ImpostazioniCode.GDExplosion3Objects3.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects1.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects2.length = 0;
gdjs.ImpostazioniCode.GDStarParticleObjects3.length = 0;
gdjs.ImpostazioniCode.GDAvviaObjects1.length = 0;
gdjs.ImpostazioniCode.GDAvviaObjects2.length = 0;
gdjs.ImpostazioniCode.GDAvviaObjects3.length = 0;
gdjs.ImpostazioniCode.GDFalsoObjects1.length = 0;
gdjs.ImpostazioniCode.GDFalsoObjects2.length = 0;
gdjs.ImpostazioniCode.GDFalsoObjects3.length = 0;
gdjs.ImpostazioniCode.GDVeroObjects1.length = 0;
gdjs.ImpostazioniCode.GDVeroObjects2.length = 0;
gdjs.ImpostazioniCode.GDVeroObjects3.length = 0;
gdjs.ImpostazioniCode.GDImpostazioni2Objects1.length = 0;
gdjs.ImpostazioniCode.GDImpostazioni2Objects2.length = 0;
gdjs.ImpostazioniCode.GDImpostazioni2Objects3.length = 0;
gdjs.ImpostazioniCode.GDimpostazioniObjects1.length = 0;
gdjs.ImpostazioniCode.GDimpostazioniObjects2.length = 0;
gdjs.ImpostazioniCode.GDimpostazioniObjects3.length = 0;
gdjs.ImpostazioniCode.GDHomeObjects1.length = 0;
gdjs.ImpostazioniCode.GDHomeObjects2.length = 0;
gdjs.ImpostazioniCode.GDHomeObjects3.length = 0;
gdjs.ImpostazioniCode.GDRetry2Objects1.length = 0;
gdjs.ImpostazioniCode.GDRetry2Objects2.length = 0;
gdjs.ImpostazioniCode.GDRetry2Objects3.length = 0;


return;

}

gdjs['ImpostazioniCode'] = gdjs.ImpostazioniCode;
